### ISSUE TITLE
Preflight Docker container with PostgreSQL database: opts.uid is NaN

### ISSUE THREAD

**Issue by karlhorky** [upleveled/preflight#588]
One of the [latest Preflight test runs](https://github.com/upleveled/pern-extensive-immersive-fall-2024-atvie/issues/114#issuecomment-2418894489) failed with the error `The "options.uid" property must be int32. Received type number (NaN)`:

```
(node:1) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Cloning https://github.com/LrDevEng/next-ecommerce-store...
Installing dependencies...
Setting up PostgreSQL database...
file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/return/final-error.js:6
	return new ErrorClass(message, options);
	       ^

ExecaError: Command failed with ERR_INVALID_ARG_TYPE: bash ./scripts/alpine-postgresql-setup-and-start.sh
The "options.uid" property must be int32. Received type number (NaN)
    at getFinalError (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/return/result.js:108:16)
    at makeEarlyError (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/return/result.js:45:7)
    at handleEarlyError (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/return/early-error.js:21:21)
    at spawnSubprocessAsync (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/main-async.js:80:10)
    at execaCoreAsync (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/main-async.js:26:32)
    ... 2 lines matching cause stack trace ...
    at file:///preflight/clone-and-preflight.ts:74:5 {
  shortMessage: 'Command failed with ERR_INVALID_ARG_TYPE: bash ./scripts/alpine-postgresql-setup-and-start.sh\n' +
    'The "options.uid" property must be int32. Received type number (NaN)',
  originalMessage: 'The "options.uid" property must be int32. Received type number (NaN)',
  command: 'bash ./scripts/alpine-postgresql-setup-and-start.sh',
  escapedCommand: 'bash ./scripts/alpine-postgresql-setup-and-start.sh',
  cwd: '/preflight/project-to-check',
  durationMs: 3.228265,
  failed: true,
  timedOut: false,
  isCanceled: false,
  isGracefullyCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  isForcefullyTerminated: false,
  code: 'ERR_INVALID_ARG_TYPE',
  stdio: [ undefined, undefined, undefined ],
  ipcOutput: [],
  pipedFrom: [],
  [cause]: TypeError [ERR_INVALID_ARG_TYPE]: The "options.uid" property must be int32. Received type number (NaN)
      at normalizeSpawnArguments (node:child_process:586:11)
      at spawn (node:child_process:754:13)
      at spawnSubprocessAsync (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/main-async.js:78:16)
      at execaCoreAsync (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/main-async.js:26:32)
      at callBoundExeca (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/create.js:44:5)
      at boundExeca (file:///preflight/node_modules/.pnpm/execa@9.4.0/node_modules/execa/lib/methods/create.js:15:44)
      at file:///preflight/clone-and-preflight.ts:74:5 {
    code: 'ERR_INVALID_ARG_TYPE'
  }
}

Node.js v22.9.0
```

This appears to be coming from this `NaN` value for `uid` being passed here, calculated from `` Number(await execa`id -u postgres`) ``:

https://github.com/upleveled/preflight/blob/d3fbfd0e1ed57c4baaf4e3e4447455933e997edc/docker/clone-and-preflight.ts#L56-L74

We need to investigate why the `postgres` user does not return an `id` - maybe the user doesn't exist?

**Comment by karlhorky** [comment]
Maybe this was related to the recent change to add `coreutils` and `node:22-alpine`? I can't think of any other (recent) changes that would have affected this:

#587

**Comment by ProchaLu** [comment]
Error happened again with an [Ecommerce Store project](https://github.com/orgs/upleveled/projects/16/views/1?filterQuery=ecomm&pane=issue&itemId=96446111&issue=upleveled%7Cpern-extensive-immersive-winter-2025-eu%7C60) from the Winter 2025 Cohort 

```
(node:1) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Cloning https://github.com/alexneumayr/next-js-ecommerce-store...
Installing dependencies...
Setting up PostgreSQL database...
file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/return/final-error.js:6
	return new ErrorClass(message, options);
	       ^

ExecaError: Command failed with ERR_INVALID_ARG_TYPE: bash ./scripts/alpine-postgresql-setup-and-start.sh
The "options.uid" property must be int32. Received type number (NaN)
    at getFinalError (file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/return/result.js:108:16)
    at makeEarlyError (file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/return/result.js:45:7)
    at handleEarlyError (file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/return/early-error.js:21:21)
    at spawnSubprocessAsync (file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/methods/main-async.js:80:10)
    at execaCoreAsync (file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/methods/main-async.js:26:32)
    ... 2 lines matching cause stack trace ...
    at file:///preflight/clone-and-preflight.ts:74:5 {
  shortMessage: 'Command failed with ERR_INVALID_ARG_TYPE: bash ./scripts/alpine-postgresql-setup-and-start.sh\n' +
    'The "options.uid" property must be int32. Received type number (NaN)',
  originalMessage: 'The "options.uid" property must be int32. Received type number (NaN)',
  command: 'bash ./scripts/alpine-postgresql-setup-and-start.sh',
  escapedCommand: 'bash ./scripts/alpine-postgresql-setup-and-start.sh',
  cwd: '/preflight/project-to-check',
  durationMs: 1.776588,
  failed: true,
  timedOut: false,
  isCanceled: false,
  isGracefullyCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  isForcefullyTerminated: false,
  code: 'ERR_INVALID_ARG_TYPE',
  stdio: [ undefined, undefined, undefined ],
  ipcOutput: [],
  pipedFrom: [],
  [cause]: TypeError [ERR_INVALID_ARG_TYPE]: The "options.uid" property must be int32. Received type number (NaN)
      at normalizeSpawnArguments (node:child_process:584:11)
      at spawn (node:child_process:752:13)
      at spawnSubprocessAsync (file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/methods/main-async.js:78:16)
      at execaCoreAsync (file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/methods/main-async.js:26:32)
      at callBoundExeca (file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/methods/create.js:44:5)
      at boundExeca (file:///preflight/node_modules/.pnpm/execa@9.4.1/node_modules/execa/lib/methods/create.js:15:44)
      at file:///preflight/clone-and-preflight.ts:74:5 {
    code: 'ERR_INVALID_ARG_TYPE'
  }
}

Node.js v22.10.0
```
